[package]
name = "comms-relay"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "relay"
path = "./src/bin/relay/main.rs"

[[bin]]
name = "uplink"
path = "./src/bin/uplink/main.rs"

[lib]
name = "comms"
path = "./src/lib/mod.rs"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.8", features = ["macros"] }
jiff = { version = "0.2.23", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "migrate"] }
tokio = { version = "1.50.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
ulid = { version = "1.2.1", features = ["serde"] }

[lints.clippy]
pedantic = "deny"
